name: Generate Changelog

on:
    push:
        branches:
            - main

jobs:
    generate-changelog:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: Install release-please
              run: npm install release-please

            - name: Generate changelog
              run: npx release-please changelog --token=${{ secrets.GITHUB_TOKEN }} --release-type=node --repo-url="${{ github.repository }}"

            - name: Commit and push updated CHANGELOG.md
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git add CHANGELOG.md
                  git commit -m "Update changelog"
                  git push origin main
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
